zuul:
  ignoredServices: "*"
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
     GREETING-CLIENT-SERVICE:
      path: /public-web/**
     
            
# Discovery Server Access
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 
server:
  port: 8080   # HTTP (Tomcat) port
  
execution:
  isolation:
    thread:
      timeoutInMilliseconds: 3000 #This property sets the time in milliseconds after which the caller will observe a timeout and walk away from the command execution. Hystrix marks > the HystrixCommand as a TIMEOUT, and performs fallback logic.
    
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true      
      