server:  
  port: 8888 #puerto donde vamos a levantar nuestro servidor
spring:  
  application:
    name: configserver  #nombre de la aplicaci칩n
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjmendez/spring-cloud-config.git #url del git d칩nde est치n alojados los ficheros de configuraci칩n      