# Spring properties
spring:       
  application:
     name: greetings-service  # Service registers under this name
  cloud:   
    config:      
      profile: dev         
      failFast: false
      uri: http://localhost:8888


