spring:       
  application:
     name: greetings-service  # nombre del microservicio
  cloud:   
    config:      
      profile: dev #perfil que va a utilizar el microservicio (greetings-service-dev)         
      failFast: false
      uri: http://localhost:8888 #dirección del servidor de configuración (config server)